[DEVICES.UdpInteractiveDevice]
  disable = false
  type = "UdpInteractiveDevice"
  displayName = "UdpInteractiveDevice"
  groupAddress = "127.0.0.1"
  privateAddress = 60000
[DEVICES.UdpInteractiveDevice.InitArgs]
  sendBuffSizeKB = 1
  recvBuffSizeKB = 1
  sendTimeout = "3s"
  recvTimeout = "3s"
