[DEVICES.UdpOutputDevice]
  disable = false
  type = "UdpOutputDevice"
  displayName = "UdpOutputDevice"
  groupAddress = "127.0.0.1"
  privateAddress = 60000
[DEVICES.UdpOutputDevice.InitArgs]
  sendBuffSizeKB = 1
  recvBuffSizeKB = 1
  sendTimeout = "3s"
  recvTimeout = "3s"
