[DRIVERS.NopUdpDriver]
  disable = false
  type = "NopDriver"
  topics = [
    "/demo/#"
  ]
[DRIVERS.NopUdpDriver.InitArgs]
  foo = "bar"


[DRIVERS.ScriptDriver]
  disable = false
  type = "ScriptDriver"
  topics = [
    "#"
  ]
[DRIVERS.ScriptDriver.InitArgs]
  script = "./scripts/hello.lua"
