# UDP服务端模式设备
[INPUTS.UDPInputDevice]
  disable = false
  type = "UDPInputDevice"
  displayName = "UDPInputDevice"
  deviceGroup = "sample-input"
  devicePrivate = "0001"
  networkAddress = "0.0.0.0:5572"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.UDPInputDevice.InitArgs]
  bufferSize = 64
  readTimeout = "3s"
  topic = "/demo/udp/input"

# TCP服务端模式设备
[INPUTS.TCPInputDevice]
  disable = false
  type = "TCPInputDevice"
  displayName = "TCPInputDevice"
  deviceGroup = "sample-input"
  devicePrivate = "0002"
  networkAddress = "0.0.0.0:5573"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.TCPInputDevice.InitArgs]
  bufferSize = 64
  readTimeout = "3s"
  topic = "/demo/tcp/input"