# 网络服务触发器，可以接收TCP/UDP网络数据包
[INPUTS.UDPInputDevice]
  disable = false
  type = "UDPInputDevice"
  displayName = "UDPInputDevice"
  groupAddress = "0.0.0.0"
  privateAddress = "5572"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.UDPInputDevice.InitArgs]
  bufferSize = 64
  readTimeout = "3s"
  topic = "/demo/udp/input"