# UDP服务端模式设备
[INPUTS.UDPInputDevice]
  disable = false
  type = "UDPInputDevice"
  name = "UDP客户端网络输入类型设备"
  uuid = "udp@(0755001001)"
  group = "location:localhost"
  private = "port:5572"
  topic = "/demo/udp/input"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.UDPInputDevice.InitArgs]
  networkAddress = "0.0.0.0:5572"
  bufferSize = 64
  readTimeout = "3s"

# TCP服务端模式设备
[INPUTS.TCPInputDevice]
  disable = false
  type = "TCPInputDevice"
  name = "TCP客户端网络输入类型设备"
  uuid = "tcp@(0755001001)"
  group = "location:localhost"
  private = "port:5573"
  topic = "/demo/tcp/input"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.TCPInputDevice.InitArgs]
  networkAddress = "0.0.0.0:5573"
  bufferSize = 64
  readTimeout = "3s"
