# UDP服务端模式设备
[INPUTS.UDPInputDevice]
  disable = false
  type = "UDPInputDevice"
  displayName = "UDPInputDevice"
  groupAddress = "0.0.0.0"
  privateAddress = "5572"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.UDPInputDevice.InitArgs]
  bufferSize = 64
  readTimeout = "3s"
  topic = "/demo/udp/input"

# TCP服务端模式设备
[INPUTS.TCPInputDevice]
  disable = false
  type = "TCPInputDevice"
  displayName = "TCPInputDevice"
  groupAddress = "0.0.0.0"
  privateAddress = "5571"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.TCPInputDevice.InitArgs]
  bufferSize = 64
  readTimeout = "3s"
  topic = "/demo/tcp/input"