# UDP服务端模式设备
[INPUTS.UDPInputDevice]
  disable = false
  type = "UDPInputDevice"
  name = "UDP客户端网络输入类型设备"
  uuid = "udp@(0755001001)"
  topic = "/demo/udp/input"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.UDPInputDevice.InitArgs]
  networkAddress = "0.0.0.0:5572"
  bufferSize = 64
  readTimeout = "3s"

# TCP服务端模式设备
[INPUTS.TCPInputDevice]
  disable = false
  type = "TCPInputDevice"
  name = "TCP客户端网络输入类型设备"
  uuid = "tcp@(0755001001)"
  topic = "/demo/tcp/input"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.TCPInputDevice.InitArgs]
  networkAddress = "0.0.0.0:5573"
  bufferSize = 64
  readTimeout = "3s"

# 串口网络输入类型设备
[INPUTS.SerialPortInputDevice]
  disable = false
  type = "SerialPortInputDevice"
  name = "串口网络输入类型设备"
  uuid = "com@(0755001001)"
  topic = "/demo/serial/input"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.SerialPortInputDevice.InitArgs]
  bufferSize = 64
  serialPort = "COM4"
  baudRate = 115200
  dataBit = 8
  stopBits = 1
