# 网络服务触发器，可以接收TCP/UDP网络数据包
[INPUTS.UdpInputDevice]
  disable = false
  type = "UdpInputDevice"
  displayName = "UdpInputDevice"
  groupAddress = "0.0.0.0"
  privateAddress = "5572"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.UdpInputDevice.InitArgs]
  buffSizeKB = 1
  readTimeout = "3s"
  topic = "/demo/udp/input"