# UDP服务端模式设备
[INPUTS.UDPInputDevice]
  disable = false
  type = "UDPInputDevice"
  name = "UDP客户端网络输入类型设备"
  uuid = "udp@(0755001001)"
  topic = "/demo/udp/input"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.UDPInputDevice.InitArgs]
  networkAddress = "0.0.0.0:5572"
  bufferSize = 64
  readTimeout = "3s"
  
[LOGICS.NopLogicDevice]
  type = "NopLogicDevice"
  name = "数据分包逻辑设备#1"
  uuid = "udp@(0755001001)#1"
  topic = "/demo/udp/input/1"
  masterUuid = "udp@(0755001001)"
[LOGICS.NopLogicDevice.InitArgs]
  readerId = 1


# TCP服务端模式设备
[INPUTS.TCPInputDevice]
  disable = false
  type = "TCPInputDevice"
  name = "TCP客户端网络输入类型设备"
  uuid = "tcp@(0755001001)"
  topic = "/demo/tcp/input"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.TCPInputDevice.InitArgs]
  networkAddress = "0.0.0.0:5573"
  bufferSize = 64
  readTimeout = "3s"

# UDP客户端模式设备
[OUTPUTS.UDPOutputDevice]
  disable = false
  type = "UDPOutputDevice"
  name = "UDP客户端模式输出类型设备"
  uuid = "udp@(0755002001)"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[OUTPUTS.UDPOutputDevice.InitArgs]
  networkAddress = "127.0.0.1:60000"
  bufferSize = 64
  writeTimeout = "3s"

# TCP客户端模式设备
[OUTPUTS.TCPOutputDevice]
  disable = false
  type = "TCPOutputDevice"
  name = "TCP客户端模式输出类型设备"
  uuid = "tcp@(0755002001)"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[OUTPUTS.TCPOutputDevice.InitArgs]
  networkAddress = "127.0.0.1:50000"
  bufferSize = 64
  writeTimeout = "3s"

