# 测试Nop插件
[PLUGINS.NopPlugin]
  disable = false
  type = "NopPlugin"
[PLUGINS.NopPlugin.InitArgs]
  a = "b"

[INPUTS.NopInputDevice]
  type = "NopInputDevice"
  name = "定时产生输入数据#1"
  uuid = "nop@(0755001001)#1"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
  topic = "/demo/nop/input/1"
[INPUTS.NopInputDevice.InitArgs]
  period = "2s"

[INTERCEPTORS.NopInterceptor]
 disable = false
 type = "NopInterceptor"
 topics = [
   "/#"
 ]
[INTERCEPTORS.NopInterceptor.InitArgs]
 a = "b"

[DRIVERS.NopUdpDriver]
  disable = false
  type = "NopDriver"
  topics = [
    "/test/#"
  ]
[DRIVERS.NopUdpDriver.InitArgs]
  foo = "bar"

[OUTPUTS.ScriptOutput]
  disable = false
  name = "测试脚本Output"
  type = "ScriptOutput"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
  uuid = "TEST-SCRIPTING-OUTPUT"
[OUTPUTS.ScriptOutput.InitArgs]
  script = "scripts/output-capture.lua"

[DRIVERS.ScriptDriver]
  disable = false
  type = "ScriptDriver"
  topics = [
    "/demo/nop/input/+"
  ]
[DRIVERS.ScriptDriver.InitArgs]
  script = "./scripts/driver-sample.lua"
  targetUuid = "TEST-SCRIPTING-OUTPUT"

[TRIGGERS.NopTrigger]
  disable = false
  type = "NopTrigger"
  topics = [
    "/demo/#"
  ]
[TRIGGERS.NopTrigger.InitArgs]
  foo = "bar"