# UDP客户端模式设备
[OUTPUTS.UDPOutputDevice]
  disable = false
  type = "UDPOutputDevice"
  displayName = "UDPOutputDevice"
  deviceGroup = "sample-output"
  devicePrivate = "001"
  networkAddress = "127.0.0.1:60000"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[OUTPUTS.UDPOutputDevice.InitArgs]
  bufferSize = 64
  writeTimeout = "3s"

# TCP客户端模式设备
[OUTPUTS.TCPOutputDevice]
  disable = false
  type = "TCPOutputDevice"
  displayName = "TCPOutputDevice"
  deviceGroup = "sample-output"
  devicePrivate = "002"
  networkAddress = "127.0.0.1:50000"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[OUTPUTS.TCPOutputDevice.InitArgs]
  bufferSize = 64
  writeTimeout = "3s"
