# UDP客户端模式设备
[OUTPUTS.UDPOutputDevice]
  disable = false
  type = "UDPOutputDevice"
  displayName = "UDPOutputDevice"
  groupAddress = "127.0.0.1"
  privateAddress = 60000
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[OUTPUTS.UDPOutputDevice.InitArgs]
  bufferSize = 64
  writeTimeout = "3s"

# TCP客户端模式设备
[OUTPUTS.TCPOutputDevice]
  disable = false
  type = "TCPOutputDevice"
  displayName = "TCPOutputDevice"
  groupAddress = "127.0.0.1"
  privateAddress = 50000
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[OUTPUTS.TCPOutputDevice.InitArgs]
  bufferSize = 64
  writeTimeout = "3s"
