# UDP客户端模式设备
[OUTPUTS.UDPOutputDevice]
  disable = false
  type = "UDPOutputDevice"
  name = "UDP客户端模式输出类型设备"
  uuid = "udp@(0755002001)"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[OUTPUTS.UDPOutputDevice.InitArgs]
  networkAddress = "127.0.0.1:60000"
  bufferSize = 64
  writeTimeout = "3s"

# TCP客户端模式设备
[OUTPUTS.TCPOutputDevice]
  disable = false
  type = "TCPOutputDevice"
  name = "TCP客户端模式输出类型设备"
  uuid = "tcp@(0755002001)"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[OUTPUTS.TCPOutputDevice.InitArgs]
  networkAddress = "127.0.0.1:50000"
  bufferSize = 64
  writeTimeout = "3s"

# 串口输出设备
[INPUTS.SerialPortOutputDevice]
  disable = false
  type = "SerialPortOutputDevice"
  name = "串口输出类型设备"
  uuid = "com@(0755001002)"
  topic = "/demo/serial/output"
  encoder = "JSONDefaultEncoder"
  decoder = "JSONDefaultDecoder"
[INPUTS.SerialPortOutputDevice.InitArgs]
  bufferSize = 64
  serialPort = "COM5"
  baudRate = 115200
  dataBit = 8
  stopBits = 1
