# 网络服务触发器，可以接收TCP/UDP网络数据包
[TRIGGERS.NetworkServerTrigger]
  disable = false
  type = "NetworkServerTrigger"
  topic = "/demo/triggers/net"
[TRIGGERS.NetworkServerTrigger.InitArgs]
  bindAddrGroup = [
    "udp://0.0.0.0:5572",
    "udp://0.0.0.0:5573"
  ]