[[constraint]]
  name = "github.com/rs/zerolog"
  version = "1.8.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/parkingwang/go-conf"
  version = "2.1.1"

[[constraint]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"
